version: 2
updates:
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: nuget
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - "Kampfmoehre"
    groups:
      roslynator:
        patterns:
          - "Roslynator.*"
      xunit:
        patterns:
          - "xunit"
          - "xunit.*"
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - "Kampfmoehre"
    commit-message:
      prefix: "ci"
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - "Kampfmoehre"
    commit-message:
      prefix: "ci"
