name: main
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: "7.0.x"
      - run: dotnet build
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: "7.0.x"
      - run: dotnet test /p:CollectCoverage=true
      - name: publish coverage report to coveralls.io
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/coverage.info
          format: lcov
  release:
    name: Semantic Release
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    needs:
      - build
      - coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: "7.0.x"
      - name: Install packages
        run: npm ci --no-fund
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: npx semantic-release